server:
  version: v0.1
  addr: :3000
  mode: debug
  static_dir: ./static
  public_dir: ./public
  # view_dir: ./view
  # upload_dir: ./storage
  max_multipart_memory: 50
  secret: Zj^D!t'd:b*1EuPluV?/v1jK@A}HC@m65i8e$-+"r!,5n'S3{Tq@QrWGO9;Y<L4

python:
  dev_host: 127.0.0.1
  test_host: 127.0.0.1
  prod_host: pano-python

database-in-docker:
  dialect: mysql
  datasource: pano:ppaannoo@tcp(mysql:3306)/pano?charset=utf8mb4&timeout=10s&parseTime=True
  dir: migrations
  table: migrations
  max_idle_conns: 2
  max_open_conns: 16

database:
  dialect: mysql
  datasource: pano:ppaannoo@tcp(mysql:3306)/pano?charset=utf8mb4&timeout=10s&parseTime=True
  dir: migrations
  table: migrations
  max_idle_conns: 2
  max_open_conns: 16