version: "3"
services:
  pano-python:
    image: poabob/pano-python:prod-1.0.0
    build: ./dist/python
    container_name: pano-python
    volumes:
      - ./dist/static:/app/go/static
    ports:
      - 5001:5001
  pano-go:
    image: poabob/pano-go:dev-1.0.0
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: pano-go
    volumes:
      - .:/app/go/
      # - 
    depends_on:
      - mysql
    ports:
      - 80:80
  mysql:
    image: mariadb:10.9
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "pano"
      MYSQL_USER: "pano"
      MYSQL_PASSWORD: "ppaannoo"
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./dist/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
