// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router_v1

import (
	"go-pano/domain/repository/clinic"
	"go-pano/domain/repository/predict"
	"go-pano/domain/repository/user"
	"go-pano/domain/service/clinic"
	"go-pano/domain/service/predict"
	"go-pano/domain/service/user"
	"go-pano/utils"
)

import (
	_ "go-pano/docs"
)

// Injectors from wire.go:

func initClinicService() clinic_service.IClinicService {
	idbInstance := utils.NewDBInstance()
	iClinicRepository := clinic_repository.NewClinicRepository(idbInstance)
	iClinicService := clinic_service.NewClinicService(iClinicRepository)
	return iClinicService
}

func initUserService() user_service.IUserService {
	idbInstance := utils.NewDBInstance()
	iUserRepository := user_repository.NewUserRepository(idbInstance)
	iUserService := user_service.NewUserService(iUserRepository)
	return iUserService
}

func initPredictService() predict_service.IPredictService {
	idbInstance := utils.NewDBInstance()
	iPredictRepository := predict_repository.NewPredictRepository(idbInstance)
	iFileUtils := utils.NewFileUtils()
	iRequestPredictService := predict_service.NewRequestPredictService()
	iPredictService := predict_service.NewPredictService(iPredictRepository, iFileUtils, iRequestPredictService)
	return iPredictService
}
