// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/predict": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "predict"
                ],
                "summary": "HTTP上傳圖片和AI辨識",
                "operationId": "1",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "請使用診所ID",
                        "name": "clinic_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "請選擇牙齒的X光圖",
                        "name": "nhicode",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "辨識資料",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.IH200"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Predict"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.IH500"
                        }
                    }
                }
            }
        },
        "/api/user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "獲取所有使用者",
                "operationId": "2",
                "responses": {
                    "200": {
                        "description": "使用者",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.IH200"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.IH500"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "更新使用者資訊",
                "operationId": "4",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名稱",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "帳號",
                        "name": "account",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "權限",
                        "name": "roles",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.IH200"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.IH500"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "新增使用者",
                "operationId": "3",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名稱",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "帳號",
                        "name": "account",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密碼",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密碼確認",
                        "name": "passconf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "權限",
                        "name": "roles",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "狀態",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.IH200"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.IH500"
                        }
                    }
                }
            }
        },
        "/api/user/password": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "更新使用者密碼",
                "operationId": "5",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密碼",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密碼確認",
                        "name": "passconf",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.IH200"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.IH500"
                        }
                    }
                }
            }
        },
        "/api/user/status": {
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "更新使用者狀態（status:0 - 已刪除，status:1 - 使用中）",
                "operationId": "6",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "狀態",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.IH200"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.IH500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Predict": {
            "type": "object",
            "properties": {
                "clinic_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "predict": {
                    "description": "JSON要顯示，但是不要存入DB",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PredictDetail"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.PredictDetail": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "bridge": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "caries": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "crown": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "embedded": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "endo": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "filling": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "imp": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "impacted": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "post": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "r_r": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "filename": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "account",
                "name",
                "passconf",
                "password",
                "roles",
                "status"
            ],
            "properties": {
                "account": {
                    "type": "string",
                    "maxLength": 64
                },
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "passconf": {
                    "type": "string"
                },
                "password": {
                    "description": "只能創建和更新",
                    "type": "string",
                    "maxLength": 1024
                },
                "roles": {
                    "type": "array",
                    "maxItems": 1024,
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "integer",
                    "maximum": 11
                },
                "user_id": {
                    "type": "integer",
                    "maximum": 11
                }
            }
        },
        "utils.IH200": {
            "type": "object",
            "properties": {
                "data": {},
                "msg": {
                    "type": "string",
                    "default": "成功"
                },
                "status": {
                    "type": "boolean",
                    "default": true
                }
            }
        },
        "utils.IH500": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "default": "desc..."
                },
                "status": {
                    "type": "boolean",
                    "default": false
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gin Go Pano",
	Description:      "Swagger API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
