// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/predict/grpc": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "predict"
                ],
                "summary": "GRPC上傳圖片和AI辨識",
                "operationId": "2",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "請使用診所ID",
                        "name": "clinic_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "請選擇牙齒的X光圖",
                        "name": "nhicode",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.IH200"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.IH500"
                        }
                    }
                }
            }
        },
        "/predict/http": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "predict"
                ],
                "summary": "HTTP上傳圖片和AI辨識",
                "operationId": "1",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "請使用診所ID",
                        "name": "clinic_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "請選擇牙齒的X光圖",
                        "name": "nhicode",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.IH200"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.IH500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utils.IH200": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "default": "成功"
                },
                "predict": {},
                "status": {
                    "type": "boolean",
                    "default": true
                }
            }
        },
        "utils.IH500": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "default": "desc..."
                },
                "status": {
                    "type": "boolean",
                    "default": false
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gin Go Pano",
	Description:      "Swagger API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
